name: CI
on:
  push:
    branches: main
    paths:
      - '.github/workflows/main.yml'
      - 'action.yml'

  pull_request:
  workflow_dispatch:

jobs:
  ci-test:
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

    - name: Build Kernel
      uses: ./
      with:
          kernel-url: https://github.com/Lafactorial/kernel_xiaomi_sm6150
          kernel-dir: sm6150
          kernel-branch: wip-ksu
          config: sweet_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: false
          ksu-version: main
          android-version: 16
          aosp-clang-version: r547379
          disable-lto: true
          anykernel3: true
